### ISSUE TITLE
Documentation not updating properly

### ISSUE THREAD

**Issue by TMRh20** [TMRh20/AutoAnalogAudio#17]
I'm not sure what exactly the problem is as I'm not too familiar yet with the auto updating of Github Pages from doxygen, so hoping @2bndy5 will come to the rescue.

**Comment by 2bndy5** [comment]
Docs are only updated on release events. If you want to work around this (without doing a release), you could comment out [this line](https://github.com/TMRh20/AutoAnalogAudio/blob/6e1d7b40592db603789a40f6be3ab8387ef932ed/.github/workflows/doxygen.yml#L42) in _.github/workflows/doxygen.yml_ (using `# this is a yml comment`). Beware that every commit on the master branch (including open pull requests) will update the docs when that line is commented out.

**Comment by 2bndy5** [comment]
I will also defer to [my latest PR on RF24Audio](https://github.com/nRF24/RF24Audio/pull/36) because that repo is also setup to update the docs on every commit to master, but notice [the doxygen workflow fails](https://github.com/nRF24/RF24Audio/pull/36/checks?check_run_id=2233273738#step:6:222) because my fork has no permission to update upstream/gh-pages branch

**Comment by 2bndy5** [comment]
ok something is weird with this repo. @TMRh20 could you confirm that the repo settings are using the root directory of the gh-pages branch? It looks like the gh-pages branch is correct.

**Comment by TMRh20** [comment]
I just created the gh-pages branch today in attempts to get it working. It is set to that now.

**Comment by 2bndy5** [comment]
was it only displaying the README before? ok docs are now properly deployed.

I also noticed some problems with the Doxyfile [concerning the INPUT ](https://github.com/TMRh20/AutoAnalogAudio/runs/2290272049?check_suite_focus=true#step:6:65)and RECURSIVE tags. They should probably be
```
INPUT                  = ./src/AutoAnalogAudio.h \
                         ./src/ESP32/AutoAnalogAudio.cpp
```
and 
```
RECURSIVE              = NO
```

Also, the [`wavStruct` used in one of the examples is also getting documented in the classes list](https://tmrh20.github.io/AutoAnalogAudio/structwavStruct.html). The above changes fix that

**Comment by 2bndy5** [comment]
Diving deeper into the documented API, I noticed that the `ramp*()` methods weren't getting documented because of the `#if defined ESP32` condition. I've started using a special macro defined by Doxyfile to force inclusion of some platform specific functionality.

Probably needles to say, but I'll submit a PR to address these doc problems

**Comment by TMRh20** [comment]
> was it only displaying the README before? 

Yeah, now working again.
